#!/usr/bin/env bash
set -euo pipefail

ROOT="/home/ljh/data1/patent"
RUNNER="${ROOT}/run_topk_wait_gpu01.sh"

RUN_PREFIX="${RUN_PREFIX:-bm25_multiseed_harder_$(date +%Y%m%d-%H%M%S)_q120_n16_s3_gpu01}"

# Fixed protocol requested by user:
# - q120_n16 baseline
# - harder candidate pool with same-IPC semantic distractors
# - cross-IPC high-similarity distractors
QUERY_SIZE="${QUERY_SIZE:-120}"
HARD_NEG_PER_QUERY="${HARD_NEG_PER_QUERY:-16}"
IPC_SEMANTIC_PER_QUERY="${IPC_SEMANTIC_PER_QUERY:-8}"
IPC_RANDOM_PER_QUERY="${IPC_RANDOM_PER_QUERY:-16}"
CROSS_IPC_HARD_PER_QUERY="${CROSS_IPC_HARD_PER_QUERY:-8}"
BM25_TOP_K="${BM25_TOP_K:-120}"
CROSS_IPC_BM25_TOP_K="${CROSS_IPC_BM25_TOP_K:-1200}"
BM25_POOL_PER_IPC="${BM25_POOL_PER_IPC:-600}"
GLOBAL_BM25_POOL_SIZE="${GLOBAL_BM25_POOL_SIZE:-60000}"

SEEDS_CSV="${SEEDS_CSV:-42,43,44}"
WAIT_SECONDS="${WAIT_SECONDS:-120}"
FREE_MEM_THRESHOLD_MB="${FREE_MEM_THRESHOLD_MB:-50000}"
UTIL_THRESHOLD="${UTIL_THRESHOLD:-20}"

RUN_PREFIX="${RUN_PREFIX}" \
QUERY_SIZE="${QUERY_SIZE}" \
HARD_NEG_PER_QUERY="${HARD_NEG_PER_QUERY}" \
IPC_SEMANTIC_PER_QUERY="${IPC_SEMANTIC_PER_QUERY}" \
IPC_RANDOM_PER_QUERY="${IPC_RANDOM_PER_QUERY}" \
CROSS_IPC_HARD_PER_QUERY="${CROSS_IPC_HARD_PER_QUERY}" \
BM25_TOP_K="${BM25_TOP_K}" \
CROSS_IPC_BM25_TOP_K="${CROSS_IPC_BM25_TOP_K}" \
BM25_POOL_PER_IPC="${BM25_POOL_PER_IPC}" \
GLOBAL_BM25_POOL_SIZE="${GLOBAL_BM25_POOL_SIZE}" \
SEEDS_CSV="${SEEDS_CSV}" \
WAIT_SECONDS="${WAIT_SECONDS}" \
FREE_MEM_THRESHOLD_MB="${FREE_MEM_THRESHOLD_MB}" \
UTIL_THRESHOLD="${UTIL_THRESHOLD}" \
"${RUNNER}"
